application: demo
version: 1
runtime: python
api_version: 1

handlers:

- url: /
  script: app.py

- url: /makenote
  script: app.py

- url: /dummy
  script: dummy.py
  login: required
  secure: always

- url: /static
  static_dir: static

- url: .*
  script: dummy.py
